<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'TrytoMqtt\\' => array($vendorDir . '/try-to/swoole_mqtt/src'),
);
